/**
 * Catálogo de capas GIS — fuente única (DRY Fase 5.2)
 */

import type { MapLayer } from "../interfaces";
import { GIS_LAYER_IDS } from "./gis.constants";

const BASE_META = {
  isSimulated: true as const,
  source: "mock" as const,
  crs: "EPSG:4326" as const,
};

export const GIS_LAYER_CATALOG: MapLayer[] = [
  {
    id: GIS_LAYER_IDS.STATIONS,
    name: "Estaciones de monitoreo",
    description: "Puntos de muestreo con clasificación ECA en tiempo real simulado.",
    type: "marker",
    visible: true,
    opacity: 1,
    zIndex: 50,
    legend: [
      { label: "Cumple ECA", color: "#10b981" },
      { label: "En alerta", color: "#f59e0b" },
      { label: "No cumple", color: "#ef4444" },
    ],
    metadata: { ...BASE_META, category: "hydrographic" },
  },
  {
    id: GIS_LAYER_IDS.RIVERS,
    name: "Ríos",
    description: "Red hídrica principal — cauces simulados a partir de estaciones.",
    type: "vector",
    visible: true,
    opacity: 0.85,
    zIndex: 40,
    legend: [{ label: "Cauce fluvial", color: "#0891b2" }],
    metadata: { ...BASE_META, category: "hydrographic", format: "mock" },
  },
  {
    id: GIS_LAYER_IDS.WATERSHEDS,
    name: "Cuencas",
    description: "Delimitación de cuencas hidrográficas de la zona de estudio.",
    type: "vector",
    visible: true,
    opacity: 0.25,
    zIndex: 10,
    legend: [{ label: "Cuenca hidrográfica", color: "#0ea5e9" }],
    metadata: { ...BASE_META, category: "hydrographic", format: "mock" },
  },
  {
    id: GIS_LAYER_IDS.QUEBRADAS,
    name: "Quebradas",
    description: "Afluentes y quebradas tributarias (simulado).",
    type: "vector",
    visible: false,
    opacity: 0.7,
    zIndex: 35,
    legend: [{ label: "Quebrada", color: "#06b6d4" }],
    metadata: { ...BASE_META, category: "hydrographic", format: "mock" },
  },
  {
    id: GIS_LAYER_IDS.DISTRICTS,
    name: "Distritos",
    description: "Límites administrativos distritales (simulados).",
    type: "vector",
    visible: false,
    opacity: 0.2,
    zIndex: 8,
    legend: [{ label: "Distrito", color: "#818cf8" }],
    metadata: { ...BASE_META, category: "administrative", format: "mock" },
  },
  {
    id: GIS_LAYER_IDS.PROVINCES,
    name: "Provincias",
    description: "Límites provinciales de Lambayeque y La Libertad.",
    type: "vector",
    visible: false,
    opacity: 0.15,
    zIndex: 6,
    legend: [{ label: "Provincia", color: "#a78bfa" }],
    metadata: { ...BASE_META, category: "administrative", format: "mock" },
  },
  {
    id: GIS_LAYER_IDS.DEPARTMENTS,
    name: "Departamentos",
    description: "Delimitación departamental — Lambayeque.",
    type: "vector",
    visible: false,
    opacity: 0.12,
    zIndex: 4,
    legend: [{ label: "Departamento", color: "#c084fc" }],
    metadata: { ...BASE_META, category: "administrative", format: "mock" },
  },
  {
    id: GIS_LAYER_IDS.NDWI,
    name: "Índice NDWI",
    description: "Normalized Difference Water Index — humedad superficial (simulado).",
    type: "raster",
    visible: false,
    opacity: 0.55,
    zIndex: 20,
    legend: [
      { label: "Bajo", color: "#1e3a5f", description: "NDWI < 0" },
      { label: "Alto", color: "#38bdf8", description: "NDWI > 0.3" },
    ],
    metadata: { ...BASE_META, category: "satellite", format: "mock" },
  },
  {
    id: GIS_LAYER_IDS.NDVI,
    name: "Índice NDVI",
    description: "Normalized Difference Vegetation Index — vegetación (simulado).",
    type: "raster",
    visible: false,
    opacity: 0.55,
    zIndex: 21,
    legend: [
      { label: "Sin vegetación", color: "#fef3c7" },
      { label: "Vegetación densa", color: "#16a34a" },
    ],
    metadata: { ...BASE_META, category: "satellite", format: "mock" },
  },
  {
    id: GIS_LAYER_IDS.MNDWI,
    name: "Índice MNDWI",
    description: "Modified NDWI — cuerpos de agua (simulado).",
    type: "raster",
    visible: false,
    opacity: 0.55,
    zIndex: 22,
    legend: [
      { label: "Seco", color: "#ecfdf5" },
      { label: "Agua", color: "#059669" },
    ],
    metadata: { ...BASE_META, category: "satellite", format: "simulated" },
  },
  {
    id: GIS_LAYER_IDS.NDTI,
    name: "Índice NDTI",
    description: "Normalized Difference Turbidity Index — turbidez (simulado).",
    type: "raster",
    visible: false,
    opacity: 0.55,
    zIndex: 23,
    legend: [
      { label: "Baja turbidez", color: "#dbeafe" },
      { label: "Alta turbidez", color: "#92400e" },
    ],
    metadata: { ...BASE_META, category: "satellite", format: "mock" },
  },
  {
    id: GIS_LAYER_IDS.SENTINEL2,
    name: "Imagen Sentinel-2",
    description: "Composición RGB simulada — preparado para GEE.",
    type: "raster",
    visible: false,
    opacity: 0.65,
    zIndex: 24,
    legend: [{ label: "Sentinel-2 SR", color: "#0891b2" }],
    metadata: { ...BASE_META, category: "satellite", format: "geotiff" },
  },
  {
    id: GIS_LAYER_IDS.ENVIRONMENTAL_RISK,
    name: "Riesgo Ambiental",
    description: "Mapa de riesgo ambiental agregado por estación (Fase 4.0).",
    type: "raster",
    visible: false,
    opacity: 0.45,
    zIndex: 30,
    legend: [
      { label: "Riesgo bajo", color: "#10b981" },
      { label: "Riesgo moderado", color: "#f59e0b" },
      { label: "Riesgo alto", color: "#ef4444" },
    ],
    metadata: { ...BASE_META, category: "analysis", format: "mock" },
  },
];
