/**
 * Navegación modular de la plataforma — Sprint 2B
 */

import type { PlatformNavSection } from "./types";

export const PLATFORM_NAVIGATION: PlatformNavSection[] = [
  {
    id: "home",
    label: "Inicio",
    emoji: "🏠",
    moduleId: "core",
    href: "/",
  },
  {
    id: "environmental-monitoring",
    label: "Monitoreo Ambiental",
    emoji: "🌊",
    moduleId: "environmental-monitoring",
    groups: [
      {
        id: "monitoring-main",
        label: "Monitoreo Ambiental",
        moduleId: "environmental-monitoring",
        items: [
          {
            id: "dashboard",
            label: "Dashboard",
            href: "/",
            icon: "dashboard",
            status: "active",
            moduleId: "environmental-monitoring",
          },
          {
            id: "stations",
            label: "Estaciones",
            href: "/estaciones",
            icon: "map",
            status: "active",
            moduleId: "environmental-monitoring",
          },
          {
            id: "sampling",
            label: "Muestreos",
            href: "/muestreos",
            icon: "sampling",
            status: "active",
            moduleId: "environmental-monitoring",
          },
          {
            id: "campaigns",
            label: "Campañas",
            href: "/campanas",
            icon: "campaigns",
            status: "active",
            moduleId: "environmental-monitoring",
          },
          {
            id: "parameters",
            label: "Parámetros",
            href: "/parametros",
            icon: "parameters",
            status: "active",
            moduleId: "environmental-monitoring",
          },
          {
            id: "environmental-assessment",
            label: "Evaluación Ambiental",
            href: "/evaluacion-ambiental",
            icon: "indicators",
            status: "active",
            moduleId: "environmental-monitoring",
          },
          {
            id: "indicators-center",
            label: "Centro de Indicadores",
            href: "/indicadores",
            icon: "chart",
            status: "active",
            moduleId: "environmental-monitoring",
          },
          {
            id: "satellite-indices",
            label: "Índices Satelitales",
            href: "/satelite",
            icon: "satellite",
            status: "active",
            moduleId: "environmental-monitoring",
          },
          {
            id: "reports",
            label: "Reportes",
            href: "/reportes",
            icon: "file",
            status: "active",
            moduleId: "environmental-monitoring",
          },
          // Rutas legacy preservadas — Sprint 2B
          {
            id: "temporal-analysis",
            label: "Análisis Temporal",
            href: "/analisis-temporal",
            icon: "temporal",
            status: "active",
            moduleId: "environmental-monitoring",
          },
          {
            id: "geospatial-center",
            label: "Centro Geoespacial",
            href: "/centro-geoespacial",
            icon: "map",
            status: "active",
            moduleId: "environmental-monitoring",
          },
          {
            id: "interactive-map",
            label: "Mapa Interactivo",
            href: "/mapa",
            icon: "map",
            status: "active",
            moduleId: "environmental-monitoring",
          },
        ],
      },
    ],
  },
  {
    id: "environmental-technologies",
    label: "Tecnologías Ambientales",
    emoji: "🧪",
    moduleId: "environmental-technologies",
    groups: [
      {
        id: "env-tech",
        label: "Tecnologías Ambientales",
        moduleId: "environmental-technologies",
        items: [
          {
            id: "biobalsa",
            label: "BioBalsa Inteligente",
            icon: "leaf",
            status: "in_development",
            badge: "En desarrollo",
            moduleId: "environmental-technologies",
          },
          {
            id: "fog-water",
            label: "Captación de Agua de Neblina",
            icon: "cloud",
            status: "coming_soon",
            badge: "Próximamente",
            moduleId: "environmental-technologies",
          },
          {
            id: "wetlands",
            label: "Humedales Artificiales",
            icon: "waves",
            status: "coming_soon",
            badge: "Próximamente",
            moduleId: "environmental-technologies",
          },
          {
            id: "restoration",
            label: "Restauración de Ecosistemas",
            icon: "tree",
            status: "coming_soon",
            badge: "Próximamente",
            moduleId: "environmental-technologies",
          },
        ],
      },
    ],
  },
  {
    id: "satellite-observation",
    label: "Observación Satelital",
    emoji: "🛰️",
    moduleId: "satellite-observation",
    groups: [
      {
        id: "satellite",
        label: "Observación Satelital",
        moduleId: "satellite-observation",
        items: [
          {
            id: "sentinel2",
            label: "Sentinel-2",
            href: "/satelite",
            icon: "satellite",
            status: "active",
            moduleId: "satellite-observation",
          },
          {
            id: "landsat",
            label: "Landsat",
            icon: "satellite",
            status: "coming_soon",
            badge: "Próximamente",
            moduleId: "satellite-observation",
          },
          {
            id: "images",
            label: "Imágenes",
            icon: "image",
            status: "coming_soon",
            badge: "Próximamente",
            moduleId: "satellite-observation",
          },
          {
            id: "indices",
            label: "Índices",
            href: "/indicadores",
            icon: "chart",
            status: "active",
            moduleId: "satellite-observation",
          },
        ],
      },
    ],
  },
  {
    id: "environmental-intelligence",
    label: "Inteligencia Ambiental",
    emoji: "🤖",
    moduleId: "environmental-intelligence",
    groups: [
      {
        id: "intelligence",
        label: "Inteligencia Ambiental",
        moduleId: "environmental-intelligence",
        items: [
          {
            id: "risk-assessment",
            label: "Evaluación de Riesgo",
            href: "/indicadores",
            icon: "brain",
            status: "active",
            moduleId: "environmental-intelligence",
          },
          {
            id: "prediction",
            label: "Predicción",
            icon: "brain",
            status: "coming_soon",
            badge: "Próximamente",
            moduleId: "environmental-intelligence",
            phase: 6,
          },
          {
            id: "alerts",
            label: "Alertas",
            icon: "activity",
            status: "coming_soon",
            badge: "Próximamente",
            moduleId: "environmental-intelligence",
            phase: 6,
          },
        ],
      },
    ],
  },
  {
    id: "administration",
    label: "Administración",
    emoji: "⚙",
    moduleId: "administration",
    groups: [
      {
        id: "admin",
        label: "Administración",
        moduleId: "administration",
        items: [
          {
            id: "system-status",
            label: "Estado del Sistema",
            href: "/admin/system-status",
            icon: "settings",
            status: "active",
            moduleId: "administration",
          },
          {
            id: "users",
            label: "Usuarios",
            icon: "users",
            status: "coming_soon",
            badge: "Próximamente",
            moduleId: "administration",
            phase: 5,
          },
        ],
      },
    ],
  },
];
